trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dockerRegistryServiceConnection: 'taskmanager-acr-connection' # À configurer
  imageRepository: 'taskmanager'
  tag: '$(Build.BuildId)'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use Python 3.x'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest
    pytest tests/ --doctest-modules --junitxml=junit/test-results.xml || true
  displayName: 'Run unit tests'
  condition: succeeded()

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)